### PR TITLE
added zuul support

### PR DESCRIPTION
**Pull request by fredericlepied**

### CODE REVIEW

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
@pc-m do we need this ?

**Comment by pc-m** [comment]
> @pc-m do we need this ?

It would have been nice to get it working but it can be converted to a draft until we need it

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Review by rgarrigue — APPROVED** [review]

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
The check fails due to the checked version not being greater than the existing one in the deb repo. Normal. Hence force merged.

**Pull request merged**
